function IDumbButtonScreenModule () {
    // No properties declared
}
module.exports = IDumbButtonScreenModule;
var instance = IDumbButtonScreenModule.prototype;
instance.onDumbButtonClick = function () {
    // AUTOGENERATED, COPY DON'T EDIT
    throw new Error("onDumbButtonClick is unimplemented");
};
 
instance.onNextScreenButtonClick = function () {
    // AUTOGENERATED, COPY DON'T EDIT
    throw new Error("onNextScreenButtonClick is unimplemented");
};
 