function IDumbListScreenModule () {
    // No properties declared
}
module.exports = IDumbListScreenModule;
var instance = IDumbListScreenModule.prototype;
/**
 * @param index {@link _.isNumber($0)}
 * @param label {@link _.isString($0)}
 */
instance.onListItemClick = function (index, label) {
    // AUTOGENERATED, COPY DON'T EDIT
    throw new Error("onListItemClick is unimplemented");
};
 